name: AnimatedMenu
version: 2.10.2
main: me.megamichiel.animatedmenu.AnimatedMenuPlugin
author: megamichiel
softdepend: [Vault, PlayerPoints, PlaceholderAPI, AnimationLib]

commands:
  animatedmenu:
    description: Plugin command
    usage: /<command>
